const images = {
    mylogo: require('./icons/mylogo-removebg-preview.png'),
    mylogowhite: require('./icons/mylogo_white-removebg-preview.png'),
    html: require('./icons/html-5-logotype.png'),
    css: require('./icons/css-3.png'),
    javascript: require('./icons/js.png'),
    reactlogo: require('./icons/atom.png'),
    bootstrap: require('./icons/bootstrap.png'),
    tailwindcss: require('./icons/tailwind-logo.png'),
    django: require('./icons/django-white.png'),
    python: require('./icons/python.png'),
    postgre: require('./icons/postgre.png'),
    seo: require('./icons/google.png'),
    shopify: require('./icons/shopify.png'),
    instagram: require('./icons/instagram.png'),
    github: require('./icons/github.png'),
    linkedin: require('./icons/linkedin.png'),
    whatsapp: require('./icons/whatsapp.png'),
    design: require('./icons/web-design.png'),
    backend: require('./icons/servers.png'),
    web: require('./icons/code.png'),
    cs50w: require('./projects/cs50w.png'),
    uny: require('./projects/engineering.jpg'),
    unity: require('./projects/Unity_logo.jpeg'),
    background: require('./bg images/pexels-tuesday-temptation-3780104.jpg'),
    ecommerce: require('./projects/ecommerce.png'),
    faketwitter: require('./projects/twitter.png'),
    fakewhatsapp: require('./projects/wsclone.png'),
    mail: require('./projects/mail.png'),
    swissgetal: require('./projects/swissgetal.png'),
    nurture: require('./projects/nurture.png'),
    unityLogo: require('./icons/unitylogo.png'),
    menu: require('./icons/menu.png'),
    overwatch: require('./icons/overwatch.png'),
    cod: require('./icons/cod.png'),
    fromsoftware: require('./icons/fromsoftware.png'),
    ui: require('./icons/ui.png'),
    illustrator: require('./icons/illustrator.png'),
    figma: require('./icons/figma.png'),
    flutter: require('./icons/flutter-white.png'),
    ai: require('./icons/ai.png'),
    engineer: require('./icons/engineer.png'),
    graduation: require('./icons/graduation-hat.png'),
    fontawesome: require('./icons/fontawesome.png'),
    check: require('./icons/check-gif.gif')
}

export default images